### ISSUE TITLE
release 2.8.0 to rubygems

### ISSUE THREAD

**Issue by ilyapoz** [metaskills/less-rails#125]
Please do

**Comment by ilyapoz** [comment]
@simi @maxd

**Comment by simi** [comment]
@maxd do you remember why it wasn't released yet?

**Comment by maxd** [comment]
I think we just forget this. 

But right now will be better to prepare new version compatible with Rails 5 and deploy it instead of 2.8.0. Seems like need to create new PR base on #124 and add Rails 5 for tests. Probably it will fix most of deprecation warnings.

I don't have free time right now but this is not a hard task and I hope somebody do it.

Workaround: use [reference to GIT repository and latest commit](http://bundler.io/git.html) in Gemfile.

**Comment by ilyapoz** [comment]
Yeah, I'm aware of the workaround, just noticed that it's still not there.

**Comment by simi** [comment]
@ilyapoz I'll push this today.

**Comment by pauloschilling** [comment]
Hi, any news on this? (or #122?) Thanks!

**Comment by simi** [comment]
https://rubygems.org/gems/less-rails/versions/2.8.0
