### ISSUE TITLE
Tests for Ruby 2.2+ and suppport for NOT using therubyracer

### ISSUE THREAD

**Issue by mikeLspohn** [metaskills/less-rails#127]
Is there anyway to get less-rails to work with mini_racer? We are using other deps that need a higher libv8 version than therubyracer (which is 2 major versions behind) supports, and it seems like a lot of other gems have moved to using mini_racer instead. 

Also, the latest version of ruby the tests run look like it's 2.1.4, is there anyway tests (if ruby version is supported) can be added for 2.2+?

Is there anyways we can get less-rails to work without therubyracer

**Comment by mwarkentin** [comment]
+1, I can't seem to get `therubyracer` to work on Alpine Linux, so having an alternative would be nice.

**Comment by brendon** [comment]
As far as I can tell, `less-rails` doesn't specify `therubyracer`, you need to add that explicitly to your `Gemfile`. What happens when you replace it with `mini_racer`? Is it that `less-rails` assumes either that gem or the java equivalent?

I've made a branch that includes tests for Ruby 2.2+: https://github.com/brendon/less-rails/tree/fix-sprockets-loading. Can you test that out and see if it works for you?

**Comment by simi** [comment]
I have updated CI to use most recent Ruby supported versions.

for alt. JS engine see https://github.com/metaskills/less-rails/issues/136

**Comment by jasonswett** [comment]
Has anyone figured out an actual answer to this?

> for alt. JS engine see #136

I don't believe #136 contains a solution.
