### ISSUE TITLE
Any way to remove/avoid therubyracer?

### ISSUE THREAD

**Issue by mikkelwf** [metaskills/less-rails#158]
Hi

I'm currently working on an old project for a client, based on rails 5.2.
The main layout uses an old version of bootstrap, based on less, and its almost impossible to remove it or rewrite it to scss without mayor work.

I want to transition all my projects to docker containers and hopefully move all my work to arm (apple M1), but as far as what i've read (and tried so far) therubyracer does NOT work on anything else than x86.

Are there no legit alternatives to therubyracer?
And why is this project relying on such an ancient and deprecated version of v8 in the first place?

**Comment by metaskills** [comment]
Hey @mikkelwf, our dependency is on less.rb, which has deps on commonjs (links below). We could care less how they are implemented. This gem aims to help with those gems integrating into Rails.

* https://github.com/cowboyd/less.rb
* https://github.com/cowboyd/commonjs.rb

> why is this project relying on such an ancient and deprecated version of v8 in the first place?

Because the projects below ours are.

**Comment by mikkelwf** [comment]
Thanks for the clarification.
I'll try to remove less from the project, seems the most feasible way to solve my issue..
