### ISSUE TITLE
railtie initializer conflict with other gem

### ISSUE THREAD

**Issue by EppO** [metaskills/less-rails#68]
Hi,

I'm the owner of the [rolify](https://github.com/EppO/rolify) gem. Some users have reported a strange bug regarding rolify's railtie that was not loaded properly at Rails boot (see EppO/rolify#156). 
I've found out that this initializer block in less-rails causes this issue:

``` ruby
initializer 'less-rails.after.load_config_initializers', :after => :load_config_initializers, :group => :all do |app|
  app.assets.context_class.extend(LessContext)
  app.assets.context_class.less_config = app.config.less
end
```

If I remove this block or just the `:after` argument, it works fine. The code inside the block doesn't seem to be the issue because if I leave the block empty, it still fails.
I don't know if it's a less-rails or a Rails issue, I would go for the latter but I wanted to have your feedback first.

**Comment by bughit** [comment]
@metaskills This must have regressed: rails/rails#35025

If this is caused by `initializer 'less-rails.before.load_config_initializers', :before => :load_config_initializers, :group => :all`, then a couple of comments:

1. gem initializers already run before app initilializers, so why is this before needed?
2. rails is probably at fault because this should not prevent the enforcement of the guarantee that app initializers will run after gems, but a fix in less-rails would be helpful

**Comment by bughit** [comment]
You mean less-rails?

If you look through rails/rails#35025, the culprit is `initializer 'less-rails.after.append_assets_path', :after => :append_assets_path`. This after condition ends up causing app initializers to run before at least some gem initializers (geocoder in the test repo)

But rafaelfranca says there's no guarantee that app inits will run after gem inits, so I suppose technically there's is no issue, however I think practically, it would be nicer if less-rails did not have such an effect (if it's avoidable).

**Comment by metaskills** [comment]
Whoops right, repo confusion.
